name: Run Lexxer Batch Every 10 Hours

on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch:

jobs:
  run-lexxer:
    runs-on: Windows Server 2025 image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run lexxer.bat
        run: |
          cd scripts
          lexxer.bat
        shell: cmd
